# Generated by Django 6.0.3 on 2026-03-24 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, choices=[('maharashtra', 'Maharashtra'), ('delhi', 'Delhi'), ('karnataka', 'Karnataka'), ('tamil_nadu', 'Tamil Nadu'), ('uttar_pradesh', 'Uttar Pradesh'), ('west_bengal', 'West Bengal'), ('rajasthan', 'Rajasthan'), ('gujarat', 'Gujarat'), ('telangana', 'Telangana'), ('kerala', 'Kerala')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('electrician', 'Electrician'), ('plumber', 'Plumber'), ('carpenter', 'Carpenter'), ('painter', 'Painter'), ('cleaner', 'Cleaner'), ('mechanic', 'Mechanic'), ('gardener', 'Gardener'), ('mover', 'Mover'), ('pest_control', 'Pest Control'), ('ac_repair', 'AC Repair')], max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('maharashtra', 'Maharashtra'), ('delhi', 'Delhi'), ('karnataka', 'Karnataka'), ('tamil_nadu', 'Tamil Nadu'), ('uttar_pradesh', 'Uttar Pradesh'), ('west_bengal', 'West Bengal'), ('rajasthan', 'Rajasthan'), ('gujarat', 'Gujarat'), ('telangana', 'Telangana'), ('kerala', 'Kerala')], max_length=30)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('bio', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
