# Generated by Django 4.2.7 on 2026-03-30 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerprofile",
            name="address_line",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="locality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customerprofile",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name="SavedAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=50)),
                ("address_line", models.CharField(max_length=255)),
                ("locality", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("maharashtra", "Maharashtra"),
                            ("delhi", "Delhi"),
                            ("karnataka", "Karnataka"),
                            ("tamil_nadu", "Tamil Nadu"),
                            ("uttar_pradesh", "Uttar Pradesh"),
                            ("west_bengal", "West Bengal"),
                            ("rajasthan", "Rajasthan"),
                            ("gujarat", "Gujarat"),
                            ("telangana", "Telangana"),
                            ("kerala", "Kerala"),
                        ],
                        max_length=30,
                    ),
                ),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("is_default", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
