# Generated by Django 4.2.7 on 2026-03-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_customerprofile_address_line_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workerprofile",
            name="city",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="is_available",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("electrician", "Electrician"),
                    ("plumber", "Plumber"),
                    ("carpenter", "Carpenter"),
                    ("painter", "Painter"),
                    ("cleaner", "Cleaner"),
                    ("mechanic", "Mechanic"),
                    ("gardener", "Gardener"),
                    ("mover", "Mover"),
                    ("pest_control", "Pest Control"),
                    ("ac_repair", "AC Repair"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workerprofile",
            name="state",
            field=models.CharField(
                choices=[
                    ("maharashtra", "Maharashtra"),
                    ("delhi", "Delhi"),
                    ("karnataka", "Karnataka"),
                    ("tamil_nadu", "Tamil Nadu"),
                    ("uttar_pradesh", "Uttar Pradesh"),
                    ("west_bengal", "West Bengal"),
                    ("rajasthan", "Rajasthan"),
                    ("gujarat", "Gujarat"),
                    ("telangana", "Telangana"),
                    ("kerala", "Kerala"),
                ],
                db_index=True,
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["service_type", "state", "is_available"],
                name="profiles_wo_service_fee9f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["service_type", "price_per_hour"],
                name="profiles_wo_service_cc7f50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workerprofile",
            index=models.Index(
                fields=["is_available", "-created_at"],
                name="profiles_wo_is_avai_4ebfd1_idx",
            ),
        ),
    ]
