# Generated by Django 4.2.7 on 2026-03-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="service_subtype",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="booking",
            name="preferred_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BookingTimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.TimeField()),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to="bookings.booking",
                    ),
                ),
            ],
            options={
                "ordering": ["time"],
            },
        ),
    ]
